part of '../../../main.dart';

//-----------------------------------------------------------------------------
Map<String, String> glossary = {
//---------------------------
  "2B tasarım":"Resim, afiş ya da billboard gibi herhangi bir düzlemde gerçekleştirilen ve sunulanlar.",
  "3B tasarım":"Heykel, bina ya da taşıt gibi tasarımların genel adı.",
  "açık kaynak":"Kullanımı, dağıtımı ve değiştirilmesi için herhangi bir telif hakkı gerektirmeyen.",
  "akıl":"Zihnin şeyler arasında mantıksal bağlar kurabilme gücü.",
  "akıl yürütme":"Genelden özele, özelden genele ve bir modelin özelliklerine bakarak ona benzeyen başka varlıkların durumları hakkında aklın kimi bağlar kurması ve çıkarımlar yapması.",
  "akıllı sistemler":"Kimi işlevler doğrultusunda algoritması karar yapılarıyla sağlanan farklı niteliklerdeki birleşenlerin oluşturduğu bütün.",
  "akıllı ürün":"Günlük hayatta belli bir gereği yerine getirmek üzere tasarlanmış amaca yönelik kimi sensörleri de kendisinde bulunduran elektro-mekanik araç.",
  "alan yazın":"Herhangi bir alana yönelik yazılan, çizilen, tartışılan ve konuşulan herşey.",
  "alan yazın araştırması":"Belirli bir konuda ilgili alanda konuyu betimleyen anahtar kavramlarla yapılan araştırma.",
  "algoritma":"Belirli bir amacı gerçekleştirmek için sınırlı ve yeterli sayıda aşamaların birbirleriyle eşgüdüm içinde çalıştıkları bir çözüm yolu.",
  "antropo-metri":"Irk, coğrafya; yaş, meslek gurupları gibi kimi etmenlere göre insan bedenini inceleyen ve kimi standartlar öneren bilim.",
  "ar-ge":"Araştırma ve geliştirme sözcüklerinin kısaltılmış durumu. Kimi organizasyonlarda inovasyon ve saha araştırması için kurulmuş birim.",
  "araç-gereç ilişkisi":"Gerece ve amaca uygun araç kullanımına ilişkin vurgu sözü. Örneğin: Balta ile beyin ameliyatı olmaz.",
  "bakım ve onarım":"Hazırlıksız yakalanmamak, kullanımın süresinin arttırmak ve ciddi arızalarla karşılaşmamak adına yapılan dönemsel iyileştirme çalışmaları.",
  "biçim":"İçsel oluşum ya da yapılandırmaların dışa yansıyan bileşke sonucu.",
  "biçimlendirme":"Bir amaca yönelik kimi yöntem ve tekniklerin dahil olduğu biçim verme süreci.",
  "bilgisayar destekli tasarım":"Tasarım sürecinde bilgisayar ve ilgili ekipmanların baskım olarak kullanılmasıyla biçim bulan süreç.",
  "bilgisayar destekli üretim":"Bilgisayar destekli tasarımın 3B Yazıcı, CNC gibi kimi gelişkin üretim araçları ile gerçekleşen üretim süreci.",
  "bilim":"Yöntem ve teknikleri daha önceden belli ve kabul edilmiş standartları olan her türden doğaya yönelik sistemli bilme ve bunun kültürünü üretme girişimi.",
  "birey odaklı tasarım":"Kişinin hedeflenen kimi özelliklerinin sürecinde baskın rol oynadığı bir tasarım yaklaşımı.",
  "bio-taklit":"Kimi tasarım problemlerinin çözmek adına benzer zorlukların doğada nasıl çözüldüğünün araştırılarak tasarım sürecinde dönüştürülmesi.",
  "Bloom sınıflandırması":"Kendi alt başlıklarına ayrılarak; zihinsel, duyuşsal ve psiko-motor gibi üç ana başlık altında eğitim sürecinin hedeflerini belirlemekte kullanılan sınıflandırma.",
  "buluş":"Daha öncesinde eşi ve benzeri var olmayan bir işleve karşılık gelen bir aracın, ilacın, hizmetin meydana getirilmiş hali.",
  "büyük veri":"Geleneksel veri işleme süreçleri ile ele alınamayacak kadar büyük ve karmaşık olan veri kümeleri.",
  "çevre dostu":"Doğanın korunmasına ve sürdürülebilirliğine önem veren her türden girişim ve üretim için kullanılan bir sıfat.",
  "çevre-bilim":"Biyolojinin bir dalı olarak, çevre-bilim canlıların çevre ve birbirleri ile olan etkileşimlerini inceleyen bir bilim.",
  "çizgi":"Doğayı soyutlama çabasının eylemsel sonucudur. Bir varlığı, bir imgeyi hem anlamak hem de anlatmakta kullanılan en yetkin ve yalın araçtır.",
  "çizim":"Bir varlığı, kavramı, imgeyi ya da imgelem sürecini çözmek, anlamak ve anlatmakta kullanılan araç.",
  "çözüm önerisi":"Belirlenmiş bir tasarım probleminin çözümüne yönelik üretilmiş birbirinden niceliksel ve niteliksel olarak farklılıklar gösteren adaylar.",
  "dayanım":"Bir maddeye uygulanan fiziksel kuvvetlere karşın o maddenin verdiği karşılık.",
  "doku":"Maddenin ritmik organizasyonu.",
  "düşünme biçimleri":"Zihinsel bir süreç olan düşünme eyleminin mantıklı olmak, somut ya da soyut olmak, gerçekçi olmak veya yaratıcı olmak gibi belli başlı özelliklere göre izlediği yollar.",
  "eleştiri":"Bir ürünü belli bir takım ölçütlere göre yeniden ele alma biçimi. Bu girişimde ürün bulundurmaya aday olduğu ölçütlere göre sınanır, uyan ve uymayan yanları belirlenir.",
  "endüstri devrimi 1":"Üretim ve dağıtım süreçlerinin 1763 yılında buhar makinesinin icadıyla çok hızlı bir biçimde değişmesiyle ortaya çıkan toplumsal, ekonomik ve teknolojik değişim.",
  "endüstri devrimi 2":"1870'li yıllardan başlayarak elektrik motorlarının bakım ve onarımı yoğun mühendislik gerektiren buhar makinelerinin yerini alması ve seri üretimin yaygınlaşmasıyla Birinci Dünya Savaşına kadarki dönem.",
  "endüstri devrimi 3":"Elektriğin üretimde yaygın olarak kullanılmasıyla elektronik sistemlerin ortaya çıkması, bilgisayarların ve programlamanın üretimin ana kavramları durumuna gelmesiyle kimlik kazanan süreç.",
  "endüstri devrimi 4.0":"Üretim birleşenlerin tümünde insan etmenini en aza indirerek süreci robotik donanımlara, onları yönetecek algoritmalara ve tüm sistemi birbiri ile işbirliğinde tutacak bilişim teknolojilerine yönlendiren yönelim.",
  "endüstriye uygulanabilirlik":"Tasarlanan bir ürünün endüstriyel üretim disiplinlerince geçerli olması",
  "endüstriyel tasarım":"Tasarımcının zihninden kullanıcının eline, kullanım sürecinde gerekebilecek teknik servis, yedek parça, bakım ve onarım aşamalarına kadarki tüm üretimin endüstri ilkelerine göre yapılması.",
  "endüstriyel tasarım ilkeleri":"Yalın, estetik, kullanıcı dostu, yenilikçi ve benzeri gibi özelliklere sahip olma ile oluşturulmuş ilkeler.",
  "enerji dönüşümü":"Aynı elektrik motorlarında elektrik enerjisinin hareket enerjisi biçimine dönüşmesinde olduğu gibi, enerjinin bir biçimden başka bir biçime geçmesi.",
  "engellilik türleri":"Doğuştan veya sonradan oluşan zihinsel ya da bedensel işlevsizlikler ve yeti-yitimleri oranlarının çeşitleri.",
  "estetik":"Bilgi-kuramsal ve varlık-bilimsel açıdan güzelliğin doğasını araştıran, tartışan ve belli birtakım normlar ortaya koymaya çalışan bir felsefe kolu.",
  "faydalı model":"Daha öncekine nitelikli yenilikler getirerek yeniden üretmenin sonucundaki tescil adı.",
  "fikir":"Belli bir alana yönelik yapılmış gözlemlerin, edinilmiş ve sınanmış bilgilerin eleştirici, mantıksal ve yaratıcı bir bakış açısıyla kimi sorunlara verdiği karşılık.",
  "fikir mülkiyeti":"Özgünlüğü ve yeniliği açısından belli bir değerde olan bir fikrin ilgili resmi kurumca üreticisine ait olduğuna ilişkin tescil.",
  "fikirleştirme":"Kavramsal olarak belli bir niteliğe ulaşmış soruna ilişkin aday çözüm önerisini somutlaştırma.",
  "geleneksel Türk evleri":"Türk kültür coğrafyaları, ekonomik ilişkileri ve üretim biçimlerinin tarihsel bağlamında aile yaşantısına karşılık olarak geliştirilmiş ve üretilmiş mimari ögeler.",
  "geri bildirim":"Fizikteki etki-tepki kavramına benzer biçimde, bir etki olarak sunulan tasarım ürününe gelen tepkiler olarak düşünülebilir.",
  "geri-dönüşüm":"Doğayı dönüşüme uğratan tasarım nesnelerinin düşük maliyetlerle doğaya geri kazandırılması.",
  "grafik tasarım":"Billboard, afiş ya da web sayfası gibi bir bildir(iş)im düzleminde resim, yazı ve çizgi gibi ögelerin sunuşu en çok verimle duruma getirmek için geliştirilmiş alan.",
  "hizmet tasarımı":"Nitelikleri önceden belirli bir hizmeti en hesaplı, en kısa sürede ve en tutarlı biçimde sunmak için gerçekleştirilen süreç.",
  "icat":"Belli bir işlevi yerine getirmede eşi ve benzeri olmayan öge.",
  "ihtiyaç":"Gereksinim. Yaşamak ve daha iyi yaşamak için kimi zaman yalın kimi zaman karmaşık olan nesnelere, hizmetlere ve süreçlere gösterilen güçlü yönelimlerin adı.",
  "imgelem":"Kimi yeni imgeler edinerek kimi var olanları düşleyim sürecine ekleyerek zihinde gerçekleşen imgelerle düşünebilme gücü.",
  "inovasyon":"Öncesinde var olanın işlevini, yapısını ve estetiğini arttırma, geliştirme, ve güncelleme",
  "iş bilimi":"Herhangi bir işin doğası gereği o sürece giren herşeyi neden-sonuç bağlamında standartlara ulaştırmaya çalışan yöntemli bilme ve sonuç çıkarma yolu.",
  "iş güvenliği":"Öncesinde nitelikleri tanımlanmış iş'in toplam verimlilik bağlamında başarıya ulaşması için alınabilecek önlemleri ve uygulamaları inceleyen bilim.",
  "isim hakkı kullanma":"Üretim, dağıtım, tanıtım ve halkla ilişkiler çerçevesinde tescilli bir niteliğe ulaşıp markalaşmış bir girişimin bir ücret ve denetlenebilirlik rızası doğrultusunda yeni model bayisi olmak.",
  "işlev":"definition",
  "işlevsellik":"definition",
  "keşif":"definition",
  "kıyaslama":"definition",
  "kompozisyon":"definition",
  "konfor":"definition",
  "kullanıcı arayüzü":"Bir hizmet birimi işlevlerinin kullanıcıya sunulmasındaki düzen",
  "kullanıcı deneyimi":"Kullanılmakta olan bir ürün ya da hizmet adına bir kullanıcının bir süre boyunca edindiği yaşantılar birikimi, düşünceler, görüşler ve seçimler",
  "kullanışlılık":"definition",
  "kültürel etkenler":"definition",
  "lisans":"definition",
  "logo":"definition",
  "maket":"definition",
  "maliyet":"definition",
  "malzeme":"definition",
  "malzeme bilimi":"definition",
  "marka":"definition",
  "marka tescili":"definition",
  "mekan":"definition",
  "mekanik özellikler":"definition",
  "mizanpaj":"definition",
  "model":"definition",
  "modelleme":"definition",
  "modüler":"definition",
  "mühendislik":"definition",
  "odak gurup":"Bir ürünün başlıca hedeflediği kimlik özellikleri iyi tanımlanmış kitle",
  "onarım":"definition",
  "organik zeka":"definition",
  "özdeşleyim":"definition",
  "özgünlük":"definition",
  "patent":"definition",
  "patent hakkı":"definition",
  "pazar yeri":"definition",
  "pazarlama":"definition",
  "performans":"definition",
  "piyasa araştırması":"definition",
  "planlama":"definition",
  "problem çözme":"definition",
  "programlama":"definition",
  "programlama dilleri":"definition",
  "proje":"definition",
  "proje raporu":"definition",
  "proje takvimi":"definition",
  "prototip":"definition",
  "reklam":"definition",
  "renk":"definition",
  "sanayi":"definition",
  "sanayi devrimleri":"definition",
  "senaryo":"definition",
  "sensör":"definition",
  "şeylerin interneti":"definition",
  "showroom":"definition",
  "sınamak":"definition",
  "sınırlılıklar":"definition",
  "şirket":"Amacı, kimliği, işleyiş biçimi önceden belli ve tescillenmiş örgüt.",
  "sorun":"Zaman, para, efor, sağlık kaybettiren ve beklentileri karşılamayan şey.",
  "strateji":"Türlü senaryolara karşı önceden hazırlanmış belli bir mantık örgüsünü izleyen plan, yaklaşım.",
  "sunum":"Bir ürünün, bir hizmetin ya da sürecin odak gurubun özellikleri, beklentileri ve deneyimleri hesaba katılarak gerçekleştirilen tanıtım etkinliği.",
  "sürdürülebilir enerji":"definition",
  "sürdürülebilirlik":"Doğayı dönüştürürken doğanın var oluş ritmine uygun olarak yeniden kullanılabilirliği, onarılabilirliği ve kolayca bakım yapılabilirliği merkeze alan tasarım ilkesi.",
  "süreç":"Başlangıcından sona kadar birbirini izleyen, belirleyen ve gerektiren aşamaların zaman dizinsel akışı.",
  "süreç tasarımı":"Bir üretim merkezinde ürünün son kullanıcıya ulaşmasına kadarki akışın tasarlanması.",
  "takım çalışması":"Üyelerinin tipik özelliklerinin takımın amacı doğrultusunda örgütlenmesi",
  "tanımlamak":"Bir şeyi onu var eden bağlama, diğer şeylerle aynı ya da farklı özelliklerini, yapısını, işlevini odağa alarak anlamlandırmak.",
  "tanıtım":"Odak gurubun karakteristik özelliklerine hitap ederek ilgili ürünün onların yaşantılarına ne gibi yararlar katacağının ve bunun için o ürünün nasıl kullanılacağının çeşitle kitle ileşimi araçlarını kullanarak gerçekleştirilen çaba.",
  "tasarı":"Gerekleri, kaynaklarıyla yapılandırılmış amacı doğrultusunda belli bir kuruluşa sahip sistematik hazırlık.",
  "tasarım":"Devingen ve dönüşümsel doğasının ortaya koyduğu bir varlık çerçevesince, sürece yönelik yeniden yapılandırılan bilişsel süreçlerin, varlığı ve değiştirilebilirliği her an sorgulanan plan adaylarıyla, yaratıcı ve yenilikçi bir yaklaşımı izleyerek, işlev ve nesne uzlaşımını ortaya koyma girişimi.",
  "tasarım problemi":"Tasarım süreci açısından ele alınmış ya da yapılandırılmış sorun.",
  "tasarım senaryosu":"Sonucunda bir ürünün hedeflendiği bir tasarım sürecini başlatabilmek için kurgulanan doğurtucu kısa öykü.",
  "tasarım süreci":"Birleşenleri tüm bilişsel süreçlere azami ölçüde talip olan sonucunda bir ürünün hedeflendiği kimi yanıyla algoritmik kimi yanıyla sezgisel yaratım çabası.",
  "tasarımcı":"Öncekini ve doğayı bir yarar doğdultusunda ürüne, hizmete ya da sürece dönüştüren tip.",
  "tasarruf":"Malzeme, zaman ve kaynakların üretim ve tüketim doğrultusunda en az ve en etkili kullanılmasına yönelik çaba.",
  "taslak":"Ürünün gelişmeye yönelik tartışmalarının ve geliştirmenin hala sürdüğü aşaması.",
  "teknik":"Pratik bir amaç doğrultusunda farklı karakterlerdeki bileşemlerinin bir araya gelerek oluşturdukları gerçekleştirim yolu.(M.Erkin)",
  "teknik çizim":"Tasarlanan ürünün endüstriyel tekniklerle gerektiği gibi üretilmesinde hataya ve yoruma yer bırakmamak için nitelikleri standartlara bağlı tekniklerle çizilerek betimlenmesi.",
  "teknik servis":"Endüstriyel üretimin sonucu olan ürünlerin son kullanıcıya uluştırılmasında, kullanılacak mekanda kurulması, arıza durumunda onarımı ve bakımı üzerine eğitim ve deneyin kazandırılmış bireylerin bulunduğu birim.",
  "teknoloji":"Edinilen bilimsel bilgilerin kimi uygulamaya yönelik amaçlar doğrultusunda yarar üretecek biçimde biriktirilmesi, sistemleştirilmesi, kullanılması ve endüstri ilkeleri uyarınca üretilmesi.",
  "telif hakkı":"Patent ya da faydalı model gibi adlarla tescillenmiş bir ürünü kullanmak ve üretmek için gereken izin.",
  "temel biçimlendirme teknikleri":"Ayırma ve birleştirmeye yönelik kesme, koparma, katlama, buruşturma, yapıştırma, vidalama, perçinleme, geçme, bağlama gibi yöntem ve tekniklerin kağıt, karton, sac levha gibi malzemeler üzerindeki uyğulama yolları.",
  "temel tasarım ilkeleri":"Hiyerarşi, zıtlık, denge, ritim, vurgu ve uyum gibi kavramların  tasarım sürecinde yer almasına yönelik ilkeler.",
  "tescil":"Bir devlet ya da uluslararası bir örgüt tarafından bir girişimin varlığının ve geçerliliğin tanınması ve kayıt altına alınması.",
  "ticari sır":"Bir hizmetin ya da sürecin neleri seçerek, hangi aşamalardan geçip nasıl yapılacağına ilişkin gizlenen bilgi.",
  "ürün":"Belli bir işlevi, gereksinimi karşılamaya yönelik teknik ve yöntemlerin algoritmik bir bütünlük kurduğu üretim sürecinin sonucu.",
  "ürün çizimi":"Hem tasarımcının bir geri-bildirimsel süreç olarak kullandığı hem de geliştirilen fikrin nasıl bir beden bulacağına yönelik fikir vermek adına girişilen süreç ve ürün.",
  "ürün çözümlemesi":"Bir ürünün birleşenlerinin örgütleşim stratejisinin incelenmesi.",
  "ürün eleştirisi":"Bir ürünün iddia ettiği özellikleri hangi niteliklerde ne oranlarda ne gibi donanımlarla ya da süreçlerle karşıladığının incelenmesi.",
  "ürün geliştirme":"Asgari bir tatminkar niteliği yakalamış bir ürünün olgunlaştırılmasına yönelik birbirini besleyen değiştiren süreçlerin odaklandığı girişim.",
  "ürün tasarımı":"Belli bir işleve, hizmete ya da sürece karşılık gelen nitelikleri önceden belirli bir üretim süreci.",
  "uygulanabilirlik":"İmgelem ile doğanın bir fikri gerçekleştirmeye yönelik azami ortak kesiti.",
  "yapay zeka":"Verileri Büyük Veri olarak soyutlanmış organik zekanın algoritmalarla benzetilmesinde, öngörülmesinde ve aşılmasında kullanılan bir zeka tipi.",
  "yaratıcılık":"Zihnin belli bir algoritmayı kabul etmeyerek o anda kendi varoluşuna göre davranma durumu.",
  "yazılım":"Amacına yönelik algoritması önceden belirli bir hedefe ulaşmada tutulan ve ögeleri birbirlerine bağlı öge.",
  "yazılım mimarisi farkı":"Aynı ya da benzer görevleri yerine getiren yazılımların bu görevleri yerine getirmekteki birimlerinin örgütlenmesine yönelik farkları.",
  "yeni":"Herhangi bir yanı ya da özelliği ile bir öncekinden farklı olan",
  "yenilik":"Eskinin eleştirisinin somutlaşmış durumu",
  "yöneylem araştırması":"Belirli koşullar altında ve  belirli bir amaç doğrultusunda ne gibi çözüm yollarının olası olduğunu bulmak için sayıtım, algoritma, anket gibi yöntemleri kullanan girişim.",
  "zihin":"Organik beynin akıl yürütme, kıyaslama, anlama, kavrama, imgeleme gibi hem bilinçli hem de bilinç dışı süreçlerinin işlevsel bütünlüğü.",
//---------------------------
};
//----------------------------------------------------------------------------
